name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install
        run: pip install mkdocs-material -r requirements.txt

      - name: Build
        if: github.event_name == 'pull_request'
        run: mkdocs build

      - name: Deploy
        if: github.event_name == 'push'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          mkdocs gh-deploy --force
